export const VAULT_ADDRESS = "0x0000000000000000000000000000000000000000";
export const VAULT_ABI = [
  "function currentState() view returns (uint8)",
  "function counterparty() view returns (address)",
  "function guardian() view returns (address)",
  "function owner() view returns (address)",
  "function commitmentHash() view returns (bytes32)",
  "function lockDuration() view returns (uint256)",
  "function lockTimestamp() view returns (uint256)",
  "function refundDelay() view returns (uint256)",
  "function depositedEthAmount() view returns (uint256)",
  "function quarantineEndTime() view returns (uint256)",
  "function quarantineInitiator() view returns (address)",
  "function nonce() view returns (uint256)",
  "function paused() view returns (bool)",
  "function deposit() payable",
  "function lock()",
  "function initiateExecution(bytes32 secret)",
  "function execute()",
  "function refund()",
  "function initiateQuarantine() payable",
  "function releaseQuarantine()",
  "function depositTokens(address token, uint256 amount)",
  "function recoverTokens(address token, address to)",
  "function recoverNFT(address token, address to, uint256 tokenId)",
  "function pause()",
  "function unpause()",
  "function scheduleUpgrade(address newImplementation)",
  "event Deposited(address indexed sender, uint256 indexed amount, uint256 timestamp)",
  "event StateChanged(uint8 indexed from, uint8 indexed to, uint256 timestamp)",
  "event Quarantined(address indexed initiator, uint256 indexed endTime)",
  "event Refunded(address indexed recipient, uint256 indexed amount, uint256 timestamp)",
];
